import datetime
import random

def main():
    print(f"Script executed at: {datetime.datetime.now()}")
    print(f"Random number: {random.randint(1, 100)}")
    print("\nThis output was generated by GitHub Actions!")

if __name__ == "__main__":
    main()
